name: mistralai_client_dart_flutter_flow
description: This is an unofficial Dart/Flutter client for the Mistral AI API.
version: 0.1.0
repository: https://github.com/nomtek/mistralai_client_dart

topics:
  - ai
  - nlp
  - llms
  - mistral

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^4.8.1
  # meta version to support Flutter SDK 3.16.0+
  # check Flutter version pinning for more details
  # https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages
  meta: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  # test version to support Flutter SDK 3.16.0+
  # check Flutter version pinning for more details
  # https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages
  test: ^1.24.0
  very_good_analysis: ^5.1.0
