name: mistralai_client_dart
description: This is an unofficial Dart/Flutter client for the Mistral AI API.
version: 0.3.0
repository: https://github.com/nomtek/mistralai_client_dart

topics:
  - ai
  - nlp
  - llms
  - mistral

environment:
  sdk: ^3.2.0

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.2.0
  json_annotation: ^4.8.1
  # meta version to support Flutter SDK 3.16.0+
  # check Flutter version pinning for more details
  # https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages
  meta: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  openapi_spec:
    git:
      url: https://github.com/gawi151/openapi_spec.git
      ref: feat/better-all-of-generation-support
  # test version to support Flutter SDK 3.16.0+
  # check Flutter version pinning for more details
  # https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages
  test: ^1.24.9
  very_good_analysis: ^5.1.0
