name: mistralai_client_dart
description: Mistral Ai client for Dart.
publish_to: none 
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.16.0
  very_good_analysis: ^5.1.0
