name: mistralai_client_dart
description: Mistral Ai client for Dart.
version: 0.0.1
repository: https://github.com/nomtek/mistralai_client_dart

environment:
  sdk: ^3.2.0

dependencies:
  http: ^1.1.2
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.16.0
  very_good_analysis: ^5.1.0
