name: Detect openapi.yaml update (Mistral's)

on:
  schedule:
    # every Sunday at 21:00 (9 PM) UTC
    - cron: "0 21 * * 0"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.2.3"
      
      - name: Check for openapi.yaml update
        run: dart run openapi_specs/update_openapi_spec.dart
